[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# JS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Sounds
[[headers]]
  for = "/sounds/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Content-Type = "audio/wav"

# SVG
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Content-Type = "image/svg+xml"

# PNG
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
